name: Terrafetch

on:
  schedule:
    - cron: "0 3 * * *"   # every night at 03:00
  workflow_dispatch:        # manual trigger when you need it

permissions:
  contents: write           # let the action push changes

jobs:
  terrafetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate README stats with Terrafetch
        uses: RoseSecurity/terrafetch@v0.3.1
        with:
          output_file: README.md      # file with the START/END markers
          collapse_output: false
          terrafetch_version: "latest"
