name: TFLint

on:
  pull_request:
    branches: [ 'main' ]
    types: [ opened, synchronize, reopened, closed, labeled, unlabeled ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4  # Using latest stable v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3  # Ensures Terraform is installed

      - name: Terraform Init
        run: terraform init
        working-directory: terraform  # Ensure we run init inside the Terraform directory

      - name: Run TFLint
        uses: The-Infra-Company/github-action-tflint-upload@ce688b1cb28478630df14818fcef896fc385c3f0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tflint_version: "v0.49.0" # TFLint added a "Bug Fix" with v0.50.0 that added .tflint.hcl as a requirement
          working_directory: "terraform/modules/vpc"
          tflint_rulesets: "aws"
          flags: >-
            --disable-rule=terraform_unused_required_providers
            --disable-rule=terraform_deprecated_index
